### ISSUE TITLE
change admin passord

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/docker-apex#2]
[user offical sql script change password](https://docs.oracle.com/en/database/oracle/application-express/21.2/htmig/downloading-installing-apex.html#GUID-7E432C6D-CECC-4977-B183-3C654380F7BF)

**Comment by chendelin1982** [comment]
apex container have server CLI , e.g
```
$ java -jar ords.war help standalone

java -jar ords.war standalone [--secure-port] [--secure-host] [--secure-cert-path] [--secure-cert-key-path] [--port] [--bind-hosts] [--apex-images] [--context-path] [--static-context-path] [--doc-root] [--parameterFile] [--config] [--debug] [--help] [--secrets] [--timing] [--verbose] [--wallet]

Launch Oracle REST Data Services in standalone mode

Options:
           [--secure-port]       HTTPS listen port, default
                                 8443

           [--secure-host]       Secure Socket Layer (SSL)
                                 certificate host name. You
                                 must specify this option if
                                 you are using --secure-port.

           [--secure-cert-path]  SSL certificate path. If you
                                 are providing the SSL
                                 certificate, you must specify
                                 the certificate location.

           [--secure-cert-key-path]SSL certificate key path. If
                                 you are providing the SSL
                                 certificate, you must specify
                                 the certificate key location.

           [--port]              HTTP listen port, default 8080

           [--bind-hosts]        Comma separated list of host
                                 names or IP addresses to
                                 identify a specific network
                                 interface on which to listen,
                                 default 0.0.0.0

           [--apex-images]       Path to the folder containing
                                 static resources required by
                                 APEX

           [--context-path]      The context path where Oracle
                                 REST Data Services is
                                 located, defaults to /ords

           [--static-context-path]The Context path where
                                 Application Express static
                                 resources are located,
                                 defaults to /i

           [--doc-root]          Points to the location where
                                 static resources, to be
                                 served under the / root
                                 server path are located.

           [--parameterFile]     Specify the location of the
                                 parameter file to use.

```

**Comment by qiaofeng1227** [comment]
推荐方案：
```
  apex:
    image: container-registry.oracle.com/database/ords:${APP_VERSION}
    container_name: ${APP_NAME} 
    depends_on:
      - oracledb
    command: ["/bin/bash", "-c", "sed -i 's/Welcome_1/Welcome_2/g' /opt/oracle/apex/setapexadmin.sql; /bin/bash  /opt/oracle/ords/startService.sh"]
    volumes:
      -  ${VOLUMES_PATH_PREFIX}/ords/:/opt/oracle/variables
    ports:
      -  ${APP_PORT}:8181
    restart: always

```
